# Read the documentation: https://fosrestbundle.readthedocs.io/en/3.x/
fos_rest:
    param_fetcher_listener: force
    body_listener: true
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: validationErrors
    allowed_methods_listener:  true
    routing_loader: false
    view:
        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
#    format_listener:
#        rules:
#            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
