framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: false
    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: ~
        cookie_secure: auto
        cookie_samesite: lax

    esi: true
    fragments: { path: /_fragment }
    php_errors:
        log: true

    trusted_hosts: '%env(TRUSTED_HOSTS)%'
    cache:
        # Put the unique name of your app here: the prefix seed
        # is used to compute stable namespaces for cache keys.
        prefix_seed: dso

        # The app cache caches to the filesystem by default.
        # Other options include:
        default_memcached_provider: '%env(MEMCACHED_URL)%'
        pools:
            app.cache.dso:
                adapter: cache.adapter.memcached
                public: false
                default_lifetime: 31536000 # 1 year

        # Redis
        #app: cache.adapter.redis
        #default_redis_provider: redis://localhost

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
#        app: cache.adapter.apcu
    form: true
    templating:
        engines:
            - twig
    validation: { enable_annotations: true }

