twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        favicon:
            size_32: /build/images/favicon/favicon-32x32.png
            size_16: /build/images/favicon/favicon-16x16.png
            apple: /build/images/favicon/apple-touch-icon.png
            manifest: /build/images/favicon/site.webmanifest
            mask_icon: /build/images/favicon/safari-pinned-tab.svg
            ms_tile: "#da532c"
            theme: "#ffffff"
        facebookId: '%env(FACEBOOK_APP_ID)%'
        facebookPage: '%env(FACEBOOK_PAGE))%'
        twitter_name: '%env(TWITTER_ACCOUNT)%'
        twitterPage: '%env(TWITTER_PAGE))%'
        analyticsId: '%env(GOOGLE_ANALYTICS_ID)%'
