twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        favicon: /favicon.ico
        facebookId: '%env(FACEBOOK_APP_ID)%'
        twitter_name: '%env(TWITTER_ACCOUNT)%'
        analyticsId: '%env(GOOGLE_ANALYTICS_ID))%'
