version: '2.2'

networks:
    default:
        driver: bridge

services:
    # PHP
    php:
        build:
            context: docker/php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        container_name: dso_php
        volumes:
            - ".:/var/www/deep-space-objects:rw"
            - "./.docker/php7-fpm/php.ini:/usr/local/etc/php/conf.d/030-custom.ini:ro"
            - "${SSH_AUTH_SOCK}:/ssh-agent:ro"
            - "~/.gitconfig:/home/site/.gitconfig:ro"
            - "~/.ssh/config:/home/site/.ssh/config:ro"
        environment:
            - SSH_AUTH_SOCK=/ssh-agent
            - TERM=xterm-color
        working_dir: /var/www/deep-space-objects

    # NGINX
    nginx:
        image: nginx:latest
        container_name: dso_nginx
        ports:
            - 80:80
        depends_on:
            - php
        volumes:
            - ./docker/nginx/default.template:/etc/nginx/conf.d/default.template
            - ./logs/nginx/:/var/log/nginx
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

    # ElasticSearch
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.0.1
        container_name: dso_elasticsearch
        hostname: elasticsearch
        environment:
            - cluster.name=demo
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - 9200:9200

    # Kibana
    kibana:
        image: docker.elastic.co/kibana/kibana:6.0.1
        container_name: dso_kibana
        links:
            - elasticsearch
        ports:
            - 5601:5601

    # Elk
#    dso_elk:
#        image: willdurand/elk
#        container_name: dso_elk
#        ports:
#            - 81:80
#        volumes:
#            - .docker/elk/logstash:/etc/logstash
#            - .docker/elk/logstash/patterns:/opt/logstash/patterns
#        volumes_from:
#          - dso_php
#          - dso_nginx

    # Redis
    dso_redis:
        image: redis:alpine
        container_name: dso_redis
        ports:
          - 6379:6379
