version: '3'

networks:
    dso_stack:
        driver: bridge

volumes:
    es_data:
        driver: local


services:
    # PHP
    php:
        build:
            context: docker/php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
                UID: ${SITE_UID}
        container_name: dso_php
        hostname: php
        ports:
            - 9000:9000
        volumes:
            - .:/var/www/deep-space-objects:cached
            - "./docker/php7-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf"
            - "${SSH_AUTH_SOCK}:/ssh-agent"
        user: ${SITE_UID}
        env_file:
          - .env
        environment:
            - SSH_AUTH_SOCK=/ssh-agent
            - TERM=xterm-color
        working_dir: /var/www/deep-space-objects
        networks:
          - dso_stack

    # NGINX
    nginx:
        build:
            context: docker/nginx
            args:
                NGINX_HOST: ${NGINX_HOST}
                UID: ${SITE_UID}
        container_name: dso_nginx
        hostname: nginx
        ports:
            - 80:80
            - 443:443
        depends_on:
            - php
        volumes:
            - .:/var/www/deep-space-objects:cached
            - ./logs/nginx/:/var/log/nginx:cached
            #- /etc/letsencrypt/:/etc/letsencrypt/
        env_file:
            - .env
        environment:
            - NGINX_HOST=${NGINX_HOST}
        networks:
            - dso_stack

    # ElasticSearch
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
        container_name: dso_elasticsearch
        hostname: elasticsearch
        volumes:
            - es_data:/usr/share/elasticsearch/data
        environment:
            - cluster.name=demo
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - 9200:9200
        networks:
            - dso_stack

    # Kibana
    kibana:
        image: docker.elastic.co/kibana/kibana:6.7.2
        container_name: dso_kibana
        links:
            - elasticsearch
        ports:
            - 5601:5601
        networks:
            - dso_stack

    # memcached
    memcached:
        image: memcached:latest
        hostname: memcached
        container_name: dso_memcached
        networks:
            - dso_stack
