version: '2.2'

networks:
    default:
        driver: bridge

volumes:
    es_data:
        driver: local

services:
    # PHP
    php:
        build:
            context: docker/php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        container_name: dso_php
        volumes:
            - ".:/var/www/deep-space-objects"
            - "${COMPOSER_CACHE_DIR}:/home/site/.composer:rw"
            - "${NPM_CACHE_DIR}:/home/site/.npm:rw,cached"
            - "./docker/php7-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf"
            - "./docker/php7-fpm/php.ini:/usr/local/etc/php/conf.d/030-custom.ini"
            - "${SSH_AUTH_SOCK}:/ssh-agent"
        env_file:
          - .env
        environment:
            - SSH_AUTH_SOCK=/ssh-agent
            - TERM=xterm-color
        working_dir: /var/www/deep-space-objects

    # NGINX
    nginx:
        build:
            context: docker/nginx
            args:
                NGINX_HOST: ${NGINX_HOST}
        container_name: dso_nginx
        ports:
            - 80:80
            - 443:443
        depends_on:
            - php
        volumes:
            - ".:/var/www/deep-space-objects"
            - ./logs/nginx/:/var/log/nginx
            - ${SSL_CERTIFICATE_CRT}:/etc/nginx/ssl/localhost.crt
            - ${SSL_CERTIFICATE_KEY}:/etc/nginx/ssl/localhost.key
        env_file:
            - .env
        environment:
            - NGINX_HOST=${NGINX_HOST}

    # ElasticSearch
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
        container_name: dso_elasticsearch
        hostname: elasticsearch
        volumes:
            - es_data:/usr/share/elasticsearch/data
        environment:
            - cluster.name=demo
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - 9200:9200

    # Kibana
    kibana:
        image: docker.elastic.co/kibana/kibana:6.5.4
        container_name: dso_kibana
        links:
            - elasticsearch
        ports:
            - 5601:5601

    # Redis
    dso_redis:
        image: redis:alpine
        container_name: dso_redis
        ports:
          - 6379:6379
