version: '2.2'

networks:
    default:
        driver: bridge

services:
    # PHP
    php:
        build:
            context: docker/php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        container_name: dso_php
        hostname: php
        user: ${SITE_UID:-1000}:${SITE_GID:-1000}
        volumes:
            - ".:/var/www/deep-space-objects:rw,cached"
            - "./docker/php7-fpm/php.ini:/usr/local/etc/php/conf.d/030-custom.ini:ro"
            - "./docker/php7-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf"
            - "${SSH_AUTH_SOCK}:/ssh-agent"
        env_file:
          - .env
        environment:
            - SSH_AUTH_SOCK=/ssh-agent
            - TERM=xterm-color
            - SITE_UID
            - SITE_GID
        working_dir: /var/www/deep-space-objects

    # NGINX
    nginx:
        image: nginx:latest
        container_name: dso_nginx
        hostname: nginx
        ports:
            - 80:80
        depends_on:
            - php
        volumes:
            - ./docker/nginx/default.template:/etc/nginx/conf.d/default.template
            - ./logs/nginx/:/var/log/nginx
        env_file:
            - .env
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

    # ElasticSearch
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.0.1
        container_name: dso_elasticsearch
        hostname: elasticsearch
        environment:
            - cluster.name=demo
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - 9200:9200

    # Kibana
    kibana:
        image: docker.elastic.co/kibana/kibana:6.0.1
        container_name: dso_kibana
        links:
            - elasticsearch
        ports:
            - 5601:5601

    # Redis
    dso_redis:
        image: redis:alpine
        container_name: dso_redis
        ports:
          - 6379:6379
