FROM nginx:latest

MAINTAINER HamHamFonFon <balistik.fonfon@gmail.com>

# install openssl
#RUN apt-get update \
#  && apt-get install -y --no-install-recommends openssl
#
#RUN mkdir /etc/nginx/ssl
#RUN cd /etc/nginx/ssl

# generate certificate
#RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/localhost.key -out /etc/nginx/ssl/localhost.crt -subj "/C=FR/ST=Montpellier/L=Montpellier/O=Global Security/OU=IT Department/CN=example.com"

#
#RUN openssl req -x509 -out localhost.crt -keyout localhost.key \
#      -newkey rsa:2048 -nodes -days 365 -sha256 \
#      -subj '/CN=localhost'

#COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint
#RUN chmod +x /usr/local/bin/docker-entrypoint

#ENTRYPOINT ["docker-entrypoint"]
