# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    app_locales: en|fr #|de|es|pt|
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    github.link: '%env(GITHUB_PAGE)%'
    paypal.link: '%env(PAYPAL_PAGE)%'
    facebook.link: '%env(FACEBOOK_PAGE)%'
    twitter.link: '%env(TWITTER_PAGE)%'
    tipeee.link: '%env(TIPEEE_PAGE)%'
    astrobinApiKey: '%env(ASTROBIN_API_KEY)%'
    astrobinApiSecret: '%env(ASTROBIN_API_SECRET)%'
    memcachedUrl: '%env(MEMCACHED_URL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $locale: "@=service('request_stack').getCurrentRequest().getLocale()"
            $defaultLocale: "%locale%"
            $listLocales: '%app_locales%'
            $githubLink: '%github.link%'
            $paypalLink: '%paypal.link%'
            $facebookLink: '%facebook.link%'
            $twitterLink: '%twitter.link%'
            $tipeeeLink: '%tipeee.link%'
            $senderMail: '%env(SENDER_MAIL)%'
            $receiverMail: '%env(GMAIL_MAIL)%'


    App\EventSubscriber\LocaleSubscriber:
        arguments: ['%kernel.default_locale%']
        tags: [kernel.event_subscriber]

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\ControllerApi\:
        resource: '../src/ControllerApi'
        tags: ['controller.service_arguments']

    App\Repository\:
        resource: '../src/Repository'

    App\Managers\:
        resource: '../src/Managers'

    # Client Elastic Search
    Elastica\Client:
        bind:
            $config:
                host: '%env(ELK_HOST)%'
                port: '%env(ELK_PORT)%'

    # Cache pool
    App\Service\Cache\CachepoolService:
        arguments:
            $cachePool: '@app.cache.dso'

    App\Service\MailService:
        autowire: true
        autoconfigure: true
        calls:
            -   method: setUserMail
                arguments:
                    - '%env(GMAIL_LOGIN)%'
            -   method: setPwdMail
                arguments:
                    - '%env(GMAIL_APP_PWD)%'

    App\Service\AstrobinService:
        arguments:
            $astrobinApiKey: '%astrobinApiKey%'
            $astrobinApiSecret: '%astrobinApiSecret%'

    # Exception listener
    App\EventListener\ExceptionListener:
        arguments: ['@twig', '%kernel.environment%']
        tags:
          - { name: kernel.event_listener, event: kernel.exception }

    # Entity listeners
    App\EventListener\GenerateTokenListener:
        tags:
            -
                name: doctrine.orm.entity_listener
                event: postPersist
                lazy: true

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    sensio_framework_extra.view.listener:
        alias: Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener
